sudo: required
services:
    - docker

before_install:
    # Run this before tests are run
    - docker build -t davidlindberg/docker-react -f Dockerfile.dev .

script:
    # Commands to be executed to (in this case) run the test suite
    - docker run -e CI=true davidlindberg/docker-react npm run test